services:
  redis:
    image: redis:7-alpine
    container_name: floxo-redis
    command:
      - redis-server
      - --requirepass
      - ${REDIS_PASSWORD}
      - --appendonly
      - "yes"
    volumes:
      - redis-data:/data
    restart: always
    networks:
      - floxo-net

  listener:
    build: .
    image: floxo-listener:latest
    container_name: floxo-listener
    env_file: .env
    environment:
      REDIS_HOST: redis
    ports:
      - "5004:3000"
    depends_on:
      - redis
    restart: always
    networks:
      - floxo-net

volumes:
  redis-data:

networks:
  floxo-net:
    name: floxo-net
